# Generated by Django 3.1.6 on 2021-02-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_user', to='customer.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('tran_type', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('tran_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tran_user', to='customer.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('dep_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_user', to='customer.authuser')),
            ],
        ),
    ]
